# Generated by Django 3.0.4 on 2020-03-10 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citations',
            fields=[
                ('cit_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cit_key', models.IntegerField()),
                ('pubmed_id', models.IntegerField(unique=True)),
                ('medline_id', models.IntegerField(unique=True)),
                ('url', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=100)),
                ('taxid_list', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DelNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.IntegerField(primary_key=True, serialize=False)),
                ('division_code', models.CharField(max_length=3)),
                ('division_name', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gencode',
            fields=[
                ('genetic_code_id', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
                ('starts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Merged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_tax_id', models.IntegerField()),
                ('new_tax_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('tax_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('parent_tax_id', models.IntegerField(verbose_name='parent_id')),
                ('rank', models.CharField(max_length=20, verbose_name='rank')),
                ('embl_code', models.IntegerField()),
                ('inherited_div_flag', models.BinaryField(default=0)),
                ('inherited_GC_flag', models.BinaryField(default=0)),
                ('mitochondrial_genetic_code_id', models.IntegerField()),
                ('inherited_MGC_flag', models.BinaryField(default=0)),
                ('GenBank_hidden_flag', models.BinaryField(default=0)),
                ('hidden_subtree_root_flag', models.BinaryField(default=0)),
                ('comments', models.CharField(max_length=100)),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxdump.Division')),
                ('genetic_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxdump.Gencode')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_txt', models.CharField(max_length=20)),
                ('unique_name', models.CharField(max_length=20, unique=True)),
                ('name_class', models.CharField(max_length=20)),
                ('tax_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxdump.Nodes')),
            ],
        ),
    ]
