# Generated by Django 3.0.4 on 2020-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxdump', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='cit_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='citations',
            name='cit_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='citations',
            name='medline_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='citations',
            name='pubmed_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='citations',
            name='taxid_list',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='citations',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='citations',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='division',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='division',
            name='division_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gencode',
            name='abbreviation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gencode',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gencode',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gencode',
            name='starts',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='name',
            name='name_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='name',
            name='name_txt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='name',
            name='unique_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='embl_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='rank',
            field=models.CharField(max_length=100, verbose_name='rank'),
        ),
        migrations.AlterUniqueTogether(
            name='citations',
            unique_together={('medline_id', 'cit_id'), ('pubmed_id', 'medline_id'), ('pubmed_id', 'cit_id')},
        ),
    ]
