# Generated by Django 3.0.4 on 2020-03-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxdump', '0004_auto_20200311_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodes',
            old_name='genetic_code_id',
            new_name='genetic_code',
        ),
    ]
