# Generated by Django 3.0.4 on 2020-03-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxdump', '0006_auto_20200311_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='unique_name',
            field=models.CharField(max_length=100),
        ),
    ]
