# Generated by Django 3.0.4 on 2020-03-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxdump', '0008_auto_20200311_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='cit_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
